### ISSUE TITLE
Set up bsdlabs.io DNS

### ISSUE THREAD

**Issue by acheronflow** [bsdlabs/bsdlabs.io#1]
bsdlabs.io will initially be hosted on a VPS provided by my company, so please create:

```
@   IN A 5.79.100.36
www IN CNAME @
```
the main A record to 5.79.100.36. and 'www' as CNAME for origin.

**Comment by koobs** [comment]
@ and www records have been updated. Gandi DNS servers dont seem to have reflected the change yet.

**Comment by koobs** [comment]
Wait, yes they have:

```
;; ANSWER SECTION:
www.bsdlabs.io.         300     IN      CNAME   bsdlabs.io.

;; ANSWER SECTION:
bsdlabs.io.             300     IN      A       5.79.100.36
```

**Comment by acheronflow** [comment]
Confirmed! Right, now to put up a nice site there.
